import type { Material } from "../types/material.types";

const MOCK_MATERIALS: Material[] = [
  {
    id: "mat-001",
    title: "Grade 9 Mathematics: Algebra Chapter 1",
    description: "Introduction to linear equations with worked examples and practice problems.",
    type: "document",
    subject: "Mathematics",
    grade: 9,
    branch: "Bole Campus",
    uploadedBy: "Mr. Tadesse Alemu",
    uploadedAt: "2026-07-28T09:00:00Z",
    size: "2.4 MB",
    downloads: 342,
  },
  {
    id: "mat-002",
    title: "English Literature: Poetry Analysis Slides",
    description: "Slide deck covering key themes and devices in the prescribed poems.",
    type: "slides",
    subject: "English",
    grade: 10,
    branch: "Bole Campus",
    uploadedBy: "Ms. Sara Bekele",
    uploadedAt: "2026-07-26T14:30:00Z",
    size: "5.8 MB",
    downloads: 217,
  },
  {
    id: "mat-003",
    title: "Physics: Newton's Laws Worksheet",
    description: "Problem set on forces and motion with answer key on the last page.",
    type: "worksheet",
    subject: "Physics",
    grade: 11,
    branch: "Bole Campus",
    uploadedBy: "Mr. Dawit Girma",
    uploadedAt: "2026-07-24T11:15:00Z",
    size: "1.1 MB",
    downloads: 486,
  },
  {
    id: "mat-004",
    title: "Biology: Cell Structure Video",
    description: "10-minute animated video explaining plant and animal cell organelles.",
    type: "video",
    subject: "Biology",
    grade: 9,
    branch: "Megenagna Campus",
    uploadedBy: "Ms. Hana Tesfaye",
    uploadedAt: "2026-07-22T08:45:00Z",
    size: "48.3 MB",
    downloads: 129,
  },
  {
    id: "mat-005",
    title: "History: Ethiopian Civilizations",
    description: "Collection of primary source links for the term research project.",
    type: "link",
    subject: "History",
    grade: 8,
    branch: "Megenagna Campus",
    uploadedBy: "Mr. Yonas Kebede",
    uploadedAt: "2026-07-20T16:00:00Z",
    size: "-",
    downloads: 98,
  },
  {
    id: "mat-006",
    title: "Chemistry: Periodic Table Handout",
    description: "Printable periodic table with common ions and molar mass references.",
    type: "document",
    subject: "Chemistry",
    grade: 10,
    branch: "Bole Campus",
    uploadedBy: "Mr. Dawit Girma",
    uploadedAt: "2026-07-18T10:20:00Z",
    size: "0.9 MB",
    downloads: 563,
  },
  {
    id: "mat-007",
    title: "Geography: Map Reading Worksheet",
    description: "Hands-on worksheet on scale, bearings, and contour lines.",
    type: "worksheet",
    subject: "Geography",
    grade: 9,
    branch: "Megenagna Campus",
    uploadedBy: "Ms. Sara Bekele",
    uploadedAt: "2026-07-15T13:10:00Z",
    size: "1.4 MB",
    downloads: 251,
  },
  {
    id: "mat-008",
    title: "Computer Science: HTML Basics Slides",
    description: "Beginner slides covering tags, attributes, and basic page structure.",
    type: "slides",
    subject: "ICT",
    grade: 10,
    branch: "Bole Campus",
    uploadedBy: "Mr. Yonas Kebede",
    uploadedAt: "2026-07-12T09:30:00Z",
    size: "3.2 MB",
    downloads: 174,
  },
  {
    id: "mat-009",
    title: "Amharic: Literature Unit 3",
    description: "Reading comprehension passages with vocabulary exercises.",
    type: "document",
    subject: "Amharic",
    grade: 7,
    branch: "Bole Campus",
    uploadedBy: "Ms. Hana Tesfaye",
    uploadedAt: "2026-07-10T15:45:00Z",
    size: "1.7 MB",
    downloads: 301,
  },
  {
    id: "mat-010",
    title: "Civics: Constitutional Rights Video",
    description: "Discussion starter video on fundamental rights and responsibilities.",
    type: "video",
    subject: "Civics",
    grade: 11,
    branch: "Megenagna Campus",
    uploadedBy: "Mr. Tadesse Alemu",
    uploadedAt: "2026-07-08T11:00:00Z",
    size: "35.6 MB",
    downloads: 87,
  },
];

export function useFetchMaterials() {
  return { data: MOCK_MATERIALS, isLoading: false };
}
