import type { UserRole } from "@/features/auth/types/user.types";

export const ALL_ROLES: readonly UserRole[] = [
  "Admin",
  "Owner",
  "Principal",
  "VicePrincipal",
  "Registrar",
  "HR",
  "Counselor",
  "Staff",
  "Parent",
  "Teacher",
  "Student",
];

export const ROUTE_ACCESS: Record<string, readonly UserRole[]> = {
  "/": ALL_ROLES,
  "/students": ["Owner", "Registrar"],
  "/parents": ["Owner", "Principal", "Registrar"],
  "/teachers": ["Owner", "Registrar"],
  "/principals": ["Owner", "Principal"],
  "/materials": ["Owner", "Principal", "Student"],
  "/schedules": ["Owner", "Registrar"],
  "/academics": ["Owner", "Principal", "VicePrincipal"],
  "/attendance": ["Owner", "Principal", "VicePrincipal", "Registrar", "HR"],
  "/classes": ["Owner", "Principal", "VicePrincipal", "Registrar"],
  "/messages": [
    "Owner",
    "Principal",
    "VicePrincipal",
    "Registrar",
    "Student",
    "Staff",
  ],
  "/schools": ["Admin"],
  "/subscriptions": ["Admin"],
  "/teacher": ["Teacher"],
  "/teacher/classes": ["Teacher"],
  "/teacher/students": ["Teacher"],
  "/teacher/timetable": ["Teacher"],
  "/teacher/attendance": ["Teacher"],
  "/teacher/gradebook": ["Teacher"],
  "/teacher/calendar": ["Teacher"],
};
